---
- name: Render the values.yaml file
  become: true
  ansible.builtin.template:
    src: templates/cnpgcluster.j2
    dest: /home/null0x/deployments/cnpgcluster.yml
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
    mode: '0755'

- name: Deploy latest version of cnpgcluster
  kubernetes.core.helm:
    name: "{{ helm_charts['cnpgcluster']['release_name'] }}"
    chart_ref: "{{ helm_charts['cnpgcluster']['release'] }}"
    create_namespace: "{{ helm_charts['cnpgcluster']['create_ns'] | bool }}"
    release_namespace: "{{ helm_charts['cnpgcluster']['namespace'] }}"
    release_state: "{{ deployment_state }}"
    values_files:
      - "/home/{{ global_primary_user }}/deployments/cnpgcluster.yml"
    update_repo_cache: true
    wait: true
  register: cc_deploy

- name: Print deployment status
  ansible.builtin.debug:
    msg: "{{ cc_deploy.stdout }}"
