---
- name: Install common dependencies
  hosts: worker04:worker05
  tasks:
    - ansible.builtin.include_role:
        name: system/common
    - ansible.builtin.include_role:
        name: system/shell/zsh
    - ansible.builtin.include_role:
        name: infrastructure/common_kubernetes
    - ansible.builtin.include_role:
        name: infrastructure/kubernetes_workers
