---
# tasks file for otomi


- name: Run the preliminary system checks
  ansible.builtin.include_tasks: checks/run_checks.yml

- name: Deploy the latest version of otomi
  when: not wp_deployed
  block:
    # - name: Deploy dependencies
    #   ansible.builtin.include_tasks: dependencies/pgsql.yml

    - name: Add the woodpecker chart repo
      ansible.builtin.include_tasks: chart/add_helm_chart.yml

    - name: Deploy the latest version of the woodpeckerci chart
      ansible.builtin.include_tasks: chart/deploy_chart.yml
