---
- name: Configure the node for management with Ansible
  ansible.builtin.include_tasks: ansible/ansible_connection.yml

- name: Ensure all appropriate kernel modules have been loaded and configured
  ansible.builtin.include_tasks: kernel/setup.yml

- name: Configure fstab and disable swap
  ansible.builtin.include_tasks: system/fstab/swap.yml

- name: Configure inter-node networking and DNS
  ansible.builtin.include_tasks: system/networking/dns/setup.yml
