---
- name: Enable passwordless sudo
  become: true
  ansible.builtin.copy:
    dest: "{{ sub_file_mappings['system']['sudoers_d']['passwordless_sudo'] }}"
    content: "{{ global_primary_user }} ALL=(ALL) NOPASSWD:ALL"

