---
- name: Check what we have already configured thusfar
  ansible.builtin.include_tasks: checks.yml

- name: Enable passwordless sudo for the primary ansible account
  when: not passwordless_active.stat.exists
  ansible.builtin.include_tasks: passwordless_sudo.yml

- name: Enable ssh forwarding
  ansible.builtin.include_tasks: ssh_forwarding.yml
