---
- name: Check if procs is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ sysutils['procs']['binary_path'] }}"
  register: has_procs

- name: Check if Eza is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ sysutils['eza']['binary_path'] }}"
  register: has_eza

- name: Check if fd-find is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ binary_mapping['sysutils']['fd_find'] }}"
  register: has_fd_find

