---
- name: Check which utilities are already installed
  ansible.builtin.include_tasks: checks.yml

- name: Install procs
  when: not has_procs.stat.exists
  ansible.builtin.include_tasks: sub_tasks/install_procs.yml

- name: Install eza
  when: not has_eza.stat.exists
  ansible.builtin.include_tasks: sub_tasks/install_eza.yml

- name: Install fd-find
  when: not has_fd_find.stat.exists
  ansible.builtin.include_tasks: sub_tasks/install_fd_find.yml

