---
# tasks file for mosquitto
- name: Generate the configmap template file.
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/configmap.j2

- name: Generate the persistent volume claim template
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/pvc.j2

- name: Create the kubernetes deployment manifest
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/deployment.j2

- name: Create the kubernetes service
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/service.j2
