---
# tasks file for mosquitto

- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/configmap.j2

- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/pvc.j2

- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/deployment.j2

- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/service.j2
