---
# - name: "install version {{ package_versions['containerd'] }}"
#   become: true
#   ansible.builtin.unarchive:
#     src: "https://github.com/containerd/containerd/releases/download/{{ package_versions['containerd'] }}/containerd-{{ package_versions['containerd'] | regex_replace('^v', '') }}-linux-amd64.tar.gz"
#     dest: "{{ mapped_directories['system']['kubernetes']['runtime']['containerd']['binaries'] }}"
#     extra_opts: [--strip-components=1]
#     remote_src: true

- name: Install the containerd binary
  become: true
  ansible.builtin.unarchive:
    src: "{{ runtime['containerd']['download'] }}"
    dest: "{{ runtime['containerd']['install_dir'] }}"
    extra_opts: [--strip-components=1]
    remote_src: true
