---
- name: Check if containerd is already installed
  ansible.builtin.include_tasks: pre_checks.yml

- name: Install the containerd binary
  when: not has_containerd_binary.stat.exists
  ansible.builtin.include_tasks: binary.yml

- name: Install the containerd systemd service
  when: not has_containerd_service.stat.exists
  ansible.builtin.include_tasks: service.yml

- name: Install the container runc
  when: not has_containerd_runc.stat.exists
  ansible.builtin.include_tasks: runc.yml

- name: Configure containerd
  when: not has_containerd_config.stat.exists
  ansible.builtin.include_tasks: config.yml
