---
# - name: Check if the containerd binary is already installed
#   become: true
#   ansible.builtin.stat:
#     path: "{{ sub_file_mappings['system']['kubernetes']['runtime']['containerd']['binary'] }}"
#   register: has_containerd_binary

# - name: Check if containerd.service is already installed
#   become: true
#   ansible.builtin.stat:
#     path: "{{ sub_file_mappings['system']['kubernetes']['runtime']['containerd']['service'] }}"
#   register: has_containerd_service

# - name: Check if containerd runc is already installed
#   become: true
#   ansible.builtin.stat:
#     path: "{{ sub_file_mappings['system']['kubernetes']['runtime']['containerd']['runc'] }}"
#   register: has_containerd_runc

# - name: Check if containerd is already configured
#   become: true
#   ansible.builtin.stat:
#     path: "{{ sub_file_mappings['system']['kubernetes']['runtime']['containerd']['config'] }}"
#   register: has_containerd_config

- name: Check if the containerd binary is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ runtime['containerd']['binary_path'] }}"
  register: has_containerd_binary

- name: Check if containerd.service is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ systemd['containerd_service']['service_path'] }}"
  register: has_containerd_service

- name: Check if containerd runc is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ runtime['containerd_runc']['binary_path'] }}"
  register: has_containerd_runc

- name: Check if containerd is already configured
  become: true
  ansible.builtin.stat:
    path: "{{ _system['containerd']['config_path'] }}"
  register: has_containerd_config

