---
- name: Pull and install the latest release of oh-my-zsh
  ansible.builtin.git:
    repo: "{{ shell['omz']['base']['download'] }}"
    dest: "{{ shell['omz']['base']['install_dir'] }}"
    depth: 1

