---
- name: Install all required dependencies
  hosts: controlplanes
  tasks:
    - name: Deploy the secondary controlplane
      ansible.builtin.include_role:
        name: kubernetes/infrastructure/deployment/controlplane/secondary
# - name: Assign utility roles
#   hosts: master01
#   tasks:
#     - name: Deploy Helm
#       ansible.builtin.include_role:
#         name: kubernetes/tooling/helm
