---
- name: Run the preliminary system checks
  ansible.builtin.include_tasks: checks/run_checks.yml

- name: Deploy the latest version of Redis Sentinel
  when: not sentinel_deployed
  block:
    # - name: Add the traefik chart repo
    #   ansible.builtin.include_tasks: chart/add_helm_chart.yml

    - name: Deploy the latest version of the Redis Sentinel chart
      ansible.builtin.include_tasks: chart/deploy_chart.yml


