---
common_kubernetes_repository:
  keyring_path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  key_url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
  repo_cmd: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
  repo_file_name: "kubernetes-apt-keyring"
  packages:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

kubernetes_default_pkgs:
  - kubelet
  - kubeadm
  - kubectl
  - kubernetes-cni

common_kubernetes_package_mapping:
  all: "{{ kubernetes_default_pkgs | list }}"
