---
- name: enable kubelet
  become: true
  ansible.builtin.service:
    name: kubelet.service
    state: started
    enabled: true
    daemon_reload: true

- name: enable containerd
  become: true
  ansible.builtin.systemd_service:
    name: containerd.service
    state: started
    daemon_reload: true
    enabled: true

- name: restart kubelet
  become: true
  ansible.builtin.systemd_service:
    name: kubelet.service
    state: restarted
    daemon_reload: true

- name: restart containerd
  become: true
  ansible.builtin.systemd_service:
    name: containerd.service
    state: restarted
    daemon_reload: true

