---
- name: Clone the Keepalived git repository
  become: true
  ansible.builtin.git:
    repo: "https://github.com/acassen/keepalived.git"
    dest: "{{ lb_sub_mapping['tmp']['keepalived'] }}"
    depth: 1

- name: Generate the automake and autoconf files
  become: true
  ansible.builtin.command: ./autogen.sh
  args:
    chdir: "{{ lb_sub_mapping['tmp']['keepalived'] }}"

- name: Configure the build parameters
  become: true
  ansible.builtin.command: ./configure
  args:
    chdir: "{{ lb_sub_mapping['tmp']['keepalived'] }}"

- name: Build Keepalived
  become: true
  community.general.make:
    chdir: "{{ lb_sub_mapping['tmp']['keepalived'] }}"

- name: Install keepalived
  become: true
  community.general.make:
    chdir: "{{ lb_sub_mapping['tmp']['keepalived'] }}"
    target: install
  notify: enable keepalived

