---
- name: Install Container Networking
  block:
    - name: Cni directory
      become: true
      ansible.builtin.file:
        path: "{{ runtime['cni']['install_dir'] }}"
        state: directory
        mode: '0755'

    - name: install the latest CNI release
      become: true
      ansible.builtin.unarchive:
        src: "{{ runtime['cni']['download'] }}"
        dest: "{{ runtime['cni']['install_dir'] }}"
        extra_opts: [--strip-components=1]
        remote_src: true
      notify:
        - restart containerd

