---
- name: Check if etcd is initialized
  become: true
  ansible.builtin.stat:
    path: "{{ etcd_sub_file_mappings['system']['kubernetes']['etcd']['config'] }}"
  register: etcd_initialized

- name: Check if a kubelet conf file exists
  become: true
  ansible.builtin.stat:
    path: "{{ etcd_sub_file_mappings['system']['systemd']['kubelet']['config'] }}"
  register: has_kubelet_conf_file

- name: Check if a kubelet unit file exists
  become: true
  ansible.builtin.stat:
    path: "{{ etcd_sub_file_mappings['system']['systemd']['kubelet']['etcd_manager'] }}"
  register: has_kubelet_unit_file

- name: Check if kubernetes is already initialized
  become: true
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['system']['kubernetes']['core']['adminconf'] }}"
  register: kubernetes_initialized

- name: Check if a kubeadm config file is already present
  become: true
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['system']['kubernetes']['core']['kubeadm'] }}"
  register: kubeadmcfg
