---
- name: Create the kubelet service dir
  become: true
  ansible.builtin.file:
    path: "{{ directory_mapping['var']['lib']['kubelet'] }}"
    recurse: true
    state: directory
    mode: '0755'
    owner: root
    group: root
- name: Touch the kewblet
  become: true
  ansible.builtin.shell: "kubeadm init phase certs ca --config {{ sub_file_mappings['system']['kubernetes']['core']['kubeadm'] }}"
- name: Yeet the kubelet
  become: true
  ansible.builtin.shell: "kubeadm init phase kubeconfig all --config {{ sub_file_mappings['system']['kubernetes']['core']['kubeadm'] }}"
- name: Create the kubelet config file v2
  become: true
  ansible.builtin.template:
    src: templates/kubeletconf.j2
    dest: "{{ sub_file_mappings['var']['lib']['kubelet']['conf'] }}"
    mode: '0755'

# - name: Yeet the kubelet conf
#   become: true
#   ansible.builtin.shell: kubeadm kubeconfig user --org system:nodes --client-name system:node:$(hostname) > /etc/kubernetes/kubelet.conf
