---
- name: Check if kubernetes is already initialized
  ansible.builtin.include_tasks: ../common/prerequisites/checks/pre_checks.yml

- name: Provision the secondary controlplanes
  when: not kubernetes_initialized.stat.exists
  block:
    - name: Create the required directories
      ansible.builtin.include_tasks: ../common/prerequisites/directories/create_directories.yml

    - name: Initialize the secondary controlplane
      become: true
      ansible.builtin.shell: "{{ kubernetes_join_command }}"
      register: kubeadm_join_output

    - name: Check if the kubeconfig file exists
      ansible.builtin.include_tasks: ../common/cluster/post_init/kubeconfig/checks.yml

    - name: Create the .kube directory
      ansible.builtin.include_tasks: ../common/cluster/post_init/kubeconfig/create_kube_dir.yml
      when: not kubernetes_config.stat.exists

    - name: Copy the kubeconfig file to ~/.kube/config
      ansible.builtin.include_tasks: ../common/cluster/post_init/kubeconfig/copy_kube_config.yml
      when: not kubernetes_config.stat.exists

