---
- name: Check if config is already symlinked
  become: true
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['home']['kube']['config'] }}"
  register: kubernetes_config


