---
- name: Ensure .kube directory exists.
  become: true
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ sub_mapping['home']['kube'] }}"
    state: directory
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
    mode: '0755'
