---
- name: Add loadbalancer VIP to hosts file
  become: true
  ansible.builtin.lineinfile:
    path: "{{ item.file }}"
    regexp: "^{{ item.entry }}"
    line: "{{ item.entry }}"
    state: present
    insertbefore: BOF
  loop:
    - {file: /etc/hosts, entry: "{{ config['vip']['ipv4'] }} {{ config['vip']['dns'] }} {{ config['vip']['dns'] }}"}
    - {file: /etc/cloud/templates/hosts.debian.tmpl, entry: "{{ config['vip']['ipv4'] }} {{ config['vip']['dns'] }} {{ config['vip']['dns'] }}"}
