---
kubernetes_commands:
  kubeadm:
    init:
      etcd:
        node: "kubeadm init phase etcd local --config /tmp/{{ groups['etcd'][0] }}/kubeadmcfg.yaml --v=5"
        ca: kubeadm init phase certs etcd-ca --v=5
    generate:
      join_etcd: "kubeadm init phase etcd local --config {{ sub_file_mappings['system']['kubernetes']['core']['kubeadm'] }} --v=5"
