---
- name: Check if Go is installed
  ansible.builtin.stat:
    path: "{{ mapped_directories['system']['golang'] }}"
  register: go_installed

- name: Check whether the go binary is already appended to PATH
  become: true
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['home']['omz']['custom']['add_go_to_path'] }}"
  register: go_binary_path
