---
- name: Check if etcd is already initialized
  ansible.builtin.include_tasks: ../common/prerequisites/checks/etcd_conf.yml

- name: Check if kubeadm is already initialized
  ansible.builtin.include_tasks: ../common/prerequisites/checks/kubernetes_cluster.yml

- name: Fire up the first etcd member
  when: not etcd_initialized.stat.exists
  block:
    - name: Create the required directories
      ansible.builtin.include_tasks: ../common/prerequisites/directories/kubernetes/create_kubernetes_dirs.yml

    - name: Create the temporary directories
      ansible.builtin.include_tasks: prerequisites/directories/tmp/node_directories.yml

    - name: Check if the kubelet is already configured
      ansible.builtin.include_tasks: ../common/prerequisites/checks/kubelet_config.yml

    - name: Ensure all facts are properly set
      ansible.builtin.include_tasks: prerequisites/ansible/command_facts.yml

    - name: Distribute ssh keys
      ansible.builtin.include_tasks: prerequisites/ansible/ssh_keys.yml

    - name: Create config files for the kubelet
      when: not has_kubelet_conf_file.stat.exists
      ansible.builtin.include_tasks: ../common/prerequisites/config/kubelet/create_kubeletconf.yml

    - name: Create kubeadm config files for all members
      when: not kubeadmcfg.stat.exists
      ansible.builtin.include_tasks: prerequisites/config/kubeadm/node_kubeadmcfg.yml

    - name: Generate certificates for all etcd members
      ansible.builtin.include_tasks: certificates/etcd_members.yml

    - name: Initialize the etcd cluster
      become: true
      ansible.builtin.shell: "{{ kubernetes_commands['kubeadm']['init']['etcd']['node'] }}"
      register: etcd_init

    - ansible.builtin.debug:
        msg: "{{ etcd_init }}"
