---
common_base_packages:
  - git
  - curl
  - zsh
  - ripgrep
  - unzip
  - gpg
  - wget
  - fd-find
  - fzf
  - jq
  - fonts-powerline

common_networking_packages:
  - netcat-traditional
  - golang-github-vishvananda-netlink-dev
  - ipvsadm
  - socat

common_python_packages:
  - python3.11-full
  - python3-netaddr
  - python3-pip
  - python3-openssl
  - python3-apt

common_python_dep_packages:
  - software-properties-common
  - libsnmp-dev
  - zlib1g-dev
  - pkg-config
  - automake
  - autoconf
  - libxtables-dev
  - libip4tc-dev
  - libip6tc-dev
  - libipset-dev
  - libnl-3-dev
  - libnl-genl-3-dev
  - libmagic-dev
  - libglib2.0-dev
  - libpcre2-dev
  - libnftnl-dev
  - libmnl-dev
  - libsystemd-dev
  - libkmod-dev
  - libnm-dev
  - libsnmp-base
  - libipset13
  - clang

common_pyenv_packages:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - libncurses5-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libffi-dev
  - liblzma-dev

common_package_mapping:
  system: "{{ common_base_packages + common_networking_packages }}"
  python:
    base: "{{ common_python_packages + common_python_dep_packages }}"
    pyenv: "{{ common_pyenv_packages }}"
