---
- name: Create configuration files for kubeadm
  become: true
  ansible.builtin.template:
    src: "{{ templates['kubeadmcfg_etcd'] }}"
    dest: "{{ global_tmp_dir }}/{{ item }}/kubeadmcfg.yaml"
    mode: "0755"
  #loop: "{{ etcd_group_hosts }}"
  loop: "{{ lookup('inventory_hostnames', 'etcd', wantlist=True) }}"
