---
- name: Provision the first controlplane
  when: inventory_hostname in groups["controlplanes"][0]
  ansible.builtin.include_tasks: primary/main.yml
- name: Provision the secondary controlplanes
  when: inventory_hostname not in groups["controlplanes"][0]
  ansible.builtin.include_tasks: secondary/main.yml
