---
# handlers file for common
- name: enable qemu_agent
  become: true
  ansible.builtin.systemd_service:
    name: qemu-guest-agent.service
    state: started
    enabled: true

- name: enable rsync
  become: true
  ansible.builtin.systemd_service:
    name: rsync.service
    state: started
    enabled: true

