---
- name: Check if the controller node has kube config
  ansible.builtin.include_tasks: kubeconfig/checks.yml

- name: Remove the old kube directory
  #when: kubernetes_config.stat.exists
  become: true
  delegate_to: localhost
  ansible.builtin.file:
    path: "/home/{{ global_primary_user }}/.kube"
    state: absent

- name: Configure the ansible controller
  #when: not kubernetes_config.stat.exists
  block:
    - name: Create the .kube directory on the ansible controller
      ansible.builtin.include_tasks: kubeconfig/create_kube_dir.yml

    - name: Copy kubeconfig to controller
      ansible.builtin.include_tasks: kubeconfig/copy_kube_config.yml


