---
- name: Print the worker node join command
  become: true
  ansible.builtin.shell: "{{ kubernetes_commands['kubeadm']['generate']['join_worker'] }}"
  register: worker_node_join_command

- name: Set the worker node join command globally.
  ansible.builtin.set_fact:
    worker_join_command: "{{ worker_node_join_command.stdout }}"
  when: worker_node_join_command.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ lookup('inventory_hostnames', 'workers', wantlist=True) }}"


