---
- name: Install kubernetes
  block:
    - name: Check whether kubernetes signing key exists
      become: true
      ansible.builtin.stat:
        path: "{{ common_kubernetes_repository['keyring_path'] }}"
      register: has_kubernetes

    - name: Add the kubernetes repository and install the appropriate packages
      when: not has_kubernetes.stat.exists
      block:
        - name: Get kubernetes key and convert to .asc
          become: true
          ansible.builtin.apt_key:
            state: present
            url: "{{ common_kubernetes_repository['key_url'] }}"
            keyring: "{{ common_kubernetes_repository['keyring_path'] }}"
          # become: true
          # ansible.builtin.get_url:
          #   url: "{{ common_kubernetes_repository['key_url'] }}"
          #   dest: "{{ common_kubernetes_repository['keyring_path'] }}"
          #   mode: '0644'
          #   force: true

        - name: Add the kubernetes repository to sources
          become: true
          ansible.builtin.apt_repository:
            repo: "{{ common_kubernetes_repository['repo_cmd'] }}"
            state: "{{ deployment_state }}"
            filename: "{{ common_kubernetes_repository['repo_file_name'] }}"
            update_cache: true



