---
- name: Check if omz is installed
  become: true
  ansible.builtin.stat:
    path: "{{ shell['omz']['base']['binary_path'] }}"
  register: omz_installed

- name: Install oh-my-zsh
  when: not omz_installed.stat.exists
  block:
    - name: Create the oh-my-zsh directory
      ansible.builtin.file:
        path: "{{ shell['omz']['base']['install_dir'] }}"
        state: directory
        mode: "0755"
        recurse: true
        owner: "{{ global_primary_user }}"
        group: "{{ global_primary_user }}"

    - name: Pull and install the latest release of oh-my-zsh
      ansible.builtin.git:
        repo: "{{ shell['omz']['base']['download'] }}"
        dest: "{{ shell['omz']['base']['install_dir'] }}"
        depth: 1

    - name: Install the desired oh-my-zsh plugins
      ansible.builtin.include_tasks: plugins/
