---
- name: Check if kubernetes is already initialized
  become: true
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['system']['kubernetes']['core']['adminconf'] }}"
  register: kubernetes_initialized

- name: Check if a kubeadm config file is already present
  become: true
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['system']['kubernetes']['core']['kubeadm'] }}"
  register: kubeadmcfg

