---

- name: Patch dpkg to stop bitching
  ansible.builtin.include_tasks: patches/patch_dpkg.yml

- name: Update and upgrade APT
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    upgrade: dist

- name: Install the latest version of all system-scoped packages
  ansible.builtin.include_tasks: installers/install_system_packages.yml

- name: Install the latest version of all python packages
  ansible.builtin.include_tasks: installers/install_python_packages.yml
