---
- name: Check if Keepalived is already installed
  ansible.builtin.include_tasks: prerequisites/checks.yml

- name: Initialize Keepalived
  #when: not has_keepalived.stat.exists
  block:
    - name: Create the required directories
      ansible.builtin.include_tasks: prerequisites/directories/keepalived.yml

    - name: Fetch, build, and install Keepalived
      ansible.builtin.include_tasks: source/build_keepalived.yml

    - name: Create the Keepalived config file
      ansible.builtin.include_tasks: ka_config/configure_keepalived.yml
