---
- name: Render the values.yaml file
  become: true
  ansible.builtin.template:
    src: templates/woodpecker.j2
    dest: /home/null0x/deployments/woodpecker.yml
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
    mode: '0755'

- name: Deploy latest version of woodpecker
  kubernetes.core.helm:
    name: "{{ helm_charts['woodpecker']['release_name'] }}"
    chart_ref: "{{ helm_charts['woodpecker']['release'] }}"
    create_namespace: "{{ helm_charts['woodpecker']['create_ns'] | bool }}"
    release_namespace: "{{ helm_charts['woodpecker']['namespace'] }}"
    release_state: "{{ deployment_state }}"
    values_files:
      - "/home/{{ global_primary_user }}/deployments/woodpecker.yml"
    update_repo_cache: true
    wait: true
  register: wp_deploy

- name: Print deployment status
  ansible.builtin.debug:
    msg: "{{ wp_deploy.stdout }}"
