---
- name: Register the clustercerts as a local fact
  ansible.builtin.set_fact:
    local_cluster_certs: "{{ cp_sub_file_mappings['system']['kubernetes']['cluster_certs'] }}"

- name: "Copy etcd certs from {{ groups['etcd'][0] }} to {{ groups['controlplanes'][0] }}"
  become: true
  loop: "{{ local_cluster_certs }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
    use_ssh_args: true
    mode: push
    rsync_path: "sudo rsync"
  delegate_to: etcd01

