---
- name: Create the k8s.conf file in modules-load
  when: not has_k8sconf.stat.exists
  become: true
  ansible.builtin.template:
    src: templates/kernel/modules_load_d/k8s.conf.j2
    dest: "{{ sub_file_mappings['system']['modules_load_d']['k8s_conf'] }}"
    mode: '0644'

- name: Load br_netfilter kernel module
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Load overlay kernel module
  become: true
  community.general.modprobe:
    name: overlay
    state: present
