---
- name: Create the k8s.conf file in sysctl.d
  become: true
  ansible.builtin.template:
    src: templates/kernel/sysctl_d/k8s.conf.j2
    dest: "{{ sub_file_mappings['system']['sysctl_d']['k8s_conf'] }}"
    mode: '0644'

- name: Enable ipv4 bridge networking
  become: true
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable ipv6 bridge networking
  become: true
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable ipv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Apply sysctl
  become: true
  ansible.builtin.shell: |
    sysctl --system

