---
- name: Add the certmanager chart repo
  kubernetes.core.helm_repository:
    name: "{{ helm_repo_map['certmanager']['name'] }}"
    repo_url: "{{ helm_repo_map['certmanager']['url'] }}"
    repo_state: "{{ deployment_state }}"
  register: certmanager_repo_add
