---
# tasks file for z2mqtt
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: frontend
    api_version: v1
    kind: Namespace
    state: "{{ deployment_state }}"
- name: Generate the middlewares.yaml file
  ansible.builtin.template:
    src: templates/configmap.j2
    dest: "{{ global_home_dir }}/z2configmap.yaml"


- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/pvc.j2
    apply: true
    wait: true

- name: Generate the middlewares.yaml file
  ansible.builtin.template:
    src: templates/deployment.j2
    dest: "{{ global_home_dir }}/z2deployment.yaml"

- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/deployment.j2
    apply: true

- name: Read definition template file from the Ansible controller file system
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: templates/service.j2
    wait: true
    apply: true
