- name: "Copy the kubernetes admin.conf to {{ sub_file_mappings['home']['kube']['config'] }}"
  become: true
  ansible.builtin.copy:
    src: "{{ sub_file_mappings['system']['kubernetes']['core']['adminconf'] }}"
    dest: "{{ sub_file_mappings['home']['kube']['config'] }}"
    remote_src: true
    mode: '0755'
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
  when: not kubernetes_config.stat.exists


