---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ helm_charts['traefik']['namespace'] }}"
    api_version: v1
    kind: Namespace
    state: "{{ deployment_state }}"

- name: Render the values.yaml file
  become: true
  ansible.builtin.template:
    src: templates/traefik.j2
    dest: /home/null0x/deployments/traefik.yml
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
    mode: '0755'

- name: Deploy latest version of traefik
  kubernetes.core.helm:
    name: "{{ helm_charts['traefik']['release_name'] }}"
    chart_ref: "{{ helm_charts['traefik']['release'] }}"
    create_namespace: "{{ helm_charts['traefik']['create_ns'] | bool }}"
    release_namespace: "{{ helm_charts['traefik']['namespace'] }}"
    values_files:
      - "/home/{{ global_primary_user }}/deployments/traefik.yml"
    release_state: "{{ deployment_state }}"
    update_repo_cache: true
    wait: true
  register: traefik_deploy

- name: Print deployment status
  ansible.builtin.debug:
    msg: "{{ traefik_deploy.stdout }}"
