---
- name: Install PyEnv
  ansible.builtin.git:
    repo: "{{ system['pyenv']['download'] }}"
    dest: "{{ system['pyenv']['install_dir'] }}"
    version: "{{ system['pyenv']['version'] }}"
    update: true

# - name: Add Pyenv to zshrc
#   ansible.builtin.blockinfile:
#     path: "{{ file_mappings['home']['zshrc'] }}"
#     block: |
#       export PYENV_ROOT="{{ system['pyenv']['install_dir'] }}"
#       [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
#       eval "$(pyenv init -)"
#       eval "$(pyenv virtualenv-init -)"
#     state: present
