---
- name: Check if Pyenv is installed
  ansible.builtin.stat:
    path: "{{ system['pyenv']['binary_path'] }}"
  register: pyenv_installed

- name: Check if PyEnv virtualenv is installed
  ansible.builtin.stat:
    path: "{{ system['pyenv_plugins']['venv']['plugin_path'] }}"
  register: pyenv_virtualenv_installed

- name: Check if PyEnv-update plugin is installed
  ansible.builtin.stat:
    path: "{{ system['pyenv_plugins']['update']['plugin_path'] }}"
  register: pyenv_update_plugin_installed

- name: Check if the desired Pyenv version is already intalled
  ansible.builtin.stat:
    path: "{{ system['pyenv']['python_binary'] }}"
  register: has_pyenv_version
