---
common_kubernetes_packages:
  - psmisc
  - procps
  - apt-transport-https
  - ca-certificates
  - cron
  - default-mta
  - rsync
  - cryptsetup

kubernetes_default_pkgs:
  - kubelet
  - kubeadm
  - kubectl
  - "kubernetes-cni"

common_kubernetes_package_mapping:
  all: "{{ common_kubernetes_packages + kubernetes_default_pkgs | list }}"

