---
- name: daemon_reload
  become: true
  ansible.builtin.shell: |
    sudo systemctl daemon-reload

- name: enable haproxy
  become: true
  ansible.builtin.systemd_service:
    name: haproxy.service
    state: started
    daemon_reload: true
    enabled: true

- name: enable keepalived
  become: true
  ansible.builtin.systemd_service:
    name: keepalived.service
    state: started
    daemon_reload: true
    enabled: true

- name: restart haproxy
  become: true
  ansible.builtin.systemd_service:
    name: haproxy.service
    state: restarted
    daemon_reload: true

- name: restart keepalived
  become: true
  ansible.builtin.systemd_service:
    name: keepalived.service
    state: restarted
    daemon_reload: true
