---
- name: Run the preliminary system checks
  ansible.builtin.include_tasks: checks/run_checks.yml

- name: Deploy the latest version of traefik
  #when: not traefik_deployed
  block:
    - name: Add the traefik chart repo
      ansible.builtin.include_tasks: chart/add_helm_chart.yml

    - name: Deploy the latest version of the traefik chart
      ansible.builtin.include_tasks: chart/deploy_chart.yml

- name: Create the cloudflare cluster issuer
  ansible.builtin.include_tasks: config/deploy_middleware.yml

- name: Create the cloudflare ssl certificate
  ansible.builtin.include_tasks: config/deploy_routes.yml

