---
- name: Run the preliminary system checks
  ansible.builtin.include_tasks: checks/run_checks.yml

- name: Deploy the latest version of Argo-cd
  when: not argocd_deployed
  block:
    - name: Add the argocd chart repo
      ansible.builtin.include_tasks: chart/add_helm_chart.yml

    - name: Deploy the latest version of the argocd chart
      ansible.builtin.include_tasks: chart/deploy_chart.yml


