---
- name: Initialize the first etcd member
  when: inventory_hostname in groups['etcd'][0]
  ansible.builtin.include_tasks: primary/main.yml

- name: Initialize the secondary etcd members
  when: not inventory_hostname in groups['etcd'][0]
  ansible.builtin.include_tasks: secondary/main.yml
