---
- name: Check if config is already symlinked
  become: true
  ansible.builtin.stat:
    path: "{{ sub_file_mappings['home']['kube']['config'] }}"
  register: kubernetes_config

- name: Ensure .kube directory exists.
  become: true
  ansible.builtin.file:
    path: "{{ sub_mapping['home']['kube'] }}"
    state: directory
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
    mode: "0755"

- name: "Copy the kubernetes admin.conf to {{ sub_file_mappings['home']['kube']['config'] }}"
  become: true
  ansible.builtin.copy:
    src: "{{ sub_file_mappings['system']['kubernetes']['core']['adminconf'] }}"
    dest: "{{ sub_file_mappings['home']['kube']['config'] }}"
    remote_src: true
    mode: "0755"
    owner: "{{ global_primary_user }}"
    group: "{{ global_primary_user }}"
  when: not kubernetes_config.stat.exists
