---
# tasks file for zitadel


- name: Run the preliminary system checks
  ansible.builtin.include_tasks: checks/run_checks.yml

- name: Deploy the latest version of Zitadel
  #when: not zitadel_deployed
  block:
    - name: Deploy dependencies
      ansible.builtin.include_tasks: dependencies/pgsql.yml

    - name: Add the zitadel chart repo
      ansible.builtin.include_tasks: chart/add_helm_chart.yml

    - name: Deploy the latest version of the zitadel chart
      ansible.builtin.include_tasks: chart/deploy_chart.yml
