---
- name: Check if kubernetes is already initialized
  ansible.builtin.include_tasks: ../common/prerequisites/checks/pre_checks.yml

- name: Provision the first controlplane
  when: not kubernetes_initialized.stat.exists
  block:
    - name: Create the required directories
      ansible.builtin.include_tasks: ../common/prerequisites/directories/create_directories.yml

    - name: Fetch etcd certificates
      ansible.builtin.include_tasks: prerequisites/certs/fetch_certs.yml

    - name: Create the kubeadm config file
      ansible.builtin.include_tasks: prerequisites/config/kubeadm.yml

    - name: Prepull kubernetes images
      ansible.builtin.include_tasks: cluster/pre_init/kubeadm/commands/pull_container_images.yml


    - name: Initialize the kubernetes controlplane
      ansible.builtin.include_tasks: cluster/pre_init/kubeadm/commands/first_init.yml

    - name: Generate the controlplane join command
      ansible.builtin.include_tasks: cluster/post_init/kubeadm/generate_cp_join_cmd.yml


    - name: Generate the worker join command
      ansible.builtin.include_tasks: cluster/post_init/kubeadm/gen_worker_join_cmd.yml


    - name: Check if the kubeconfig file exists
      ansible.builtin.include_tasks: ../common/cluster/post_init/kubeconfig/checks.yml

    - name: Create the .kube directory
      ansible.builtin.include_tasks: ../common/cluster/post_init/kubeconfig/create_kube_dir.yml
      when: not kubernetes_config.stat.exists


    - name: Copy the kubeconfig file to ~/.kube/config
      ansible.builtin.include_tasks: ../common/cluster/post_init/kubeconfig/copy_kube_config.yml
      when: not kubernetes_config.stat.exists


    - name: "Configure {{ config['cni'] }} as the cluster CNI"
      when: config['cni'] == 'flannel'
      ansible.builtin.include_tasks: "cluster/post_init/cni/install_{{ config['cni'] }}.yml"

    # # TODO: move out
    # - name: Configure cluster control on the ansible controller
    #   ansible.builtin.include_tasks: ../ansible_controller/setup_cluster_access.yml

