---
- name: Fix dpkg
  become: true
  ansible.builtin.command: dpkg --configure -a

- name: Update and upgrade APT
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    upgrade: dist

- name: Install the latest version of all required packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    force_apt_get: true
    name: "{{ common_base_packages }}"
