---
- name: Prepull kubernetes images
  become: true
  ansible.builtin.shell: "{{ kubernetes_commands['kubeadm']['pull_images'] }}"

- name: Initialize the kubernetes controlplane
  become: true
  ansible.builtin.shell: "{{ kubernetes_commands['kubeadm']['init']['controlplane'] }}"
  register: kubeadm_init_output
