---
- name: Install the latest version of all python packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    force_apt_get: true
    name: "{{ common_package_mapping['python']['base'] }}"

- name: Install the latest version of all pyenv packages
  ansible.builtin.include_tasks: install_pyenv_packages.yml
