---
- name: Fetch the kubernetes certificate key
  ansible.builtin.shell: "{{ kubernetes_commands['kubeadm']['print_certkey'] }}"
  register: kube_cert_key

- name: Print control plane join command
  become: true
  ansible.builtin.command: "{{ kubernetes_commands['kubeadm']['generate']['join_plane'] }}{{ kube_cert_key.stdout }}"
  register: control_plane_join_command

- name: Set the control plane join command globally.
  when: not inventory_hostname in item
  loop: "{{ lookup('inventory_hostnames', 'controlplanes', wantlist=True) }}"
  ansible.builtin.set_fact:
    kubernetes_join_command: "{{ control_plane_join_command.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
