---
- name: Fetch and register all etcd member ip addresses
  ansible.builtin.set_fact:
    etcd_ips: "{{ groups['etcd'] | map('extract', hostvars) | map(attribute='ansible_host') }}"

- name: Register the clustercerts as a local fact
  ansible.builtin.set_fact:
    local_cluster_certs: "{{ cp_sub_file_mappings['system']['kubernetes']['cluster_certs'] }}"

# - name: "Copy etcd certs from {{ groups['etcd'][0] }} to {{ groups['controlplanes'][0] }}"
#   become: true
#   loop: "{{ local_cluster_certs }}"
#   ansible.posix.synchronize:
#     src: "{{ item }}"
#     dest: "{{ item }}"
#     use_ssh_args: true
#     mode: push
#     rsync_path: "sudo rsync"
#     ssh_args: "-i /home/null0x/.ssh/ansible_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
#   delegate_to: etcd01
# - name: "Copy etcd certs from {{ groups['etcd'][0] }} to {{ groups['controlplanes'][0] }}"
#   loop: "{{ local_cluster_certs }}"
#   ansible.posix.synchronize:
#     src: "{{ item }}"
#     dest: "{{ item }}"
#     use_ssh_args: true
#     mode: push
#     rsync_path: "sudo rsync"
#     private_key: "/home/null0x/.ssh/ansible_ed25519" # Use your actual SSH key path
#   delegate_to: etcd01
- name: Ensure the etcd directory exists on the destination node (master)
  become: true
  ansible.builtin.file:
    path: "/etc/kubernetes/pki/etcd"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "Copy etcd certs from etcd01 to master01"
  become: true
  loop: "{{ local_cluster_certs }}"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
    mode: push
    #recursive: true
  delegate_to: "{{ groups['etcd'][0] }}"
# - name: Fetch etcd certs from etcd01 to the control node
#   become: true
#   delegate_to: "{{ groups['etcd'][0] }}
#   loop: "{{ local_cluster_certs }}"
#   ansible.builtin.fetch:
#     src: "{{ item }}"
#     dest: "/tmp/etcd_certs/"
#     flat: yes
#     fail_on_missing: yes
#     validate_checksum: yes
#
# - name: Copy certs to master01
#   loop: "{{ local_cluster_certs }}"
#   delegate_to: master01
#   ansible.builtin.copy:
#     src: "/tmp/etcd_certs/{{ item | basename }}"
#     dest: "{{ item }}"
#     owner: root
#     group: root
#     mode: "0644"
#     remote_src: true
