---
- name: Install the desired system utilities
  ansible.builtin.include_tasks: utilities/install_utilities.yml

- name: Install oh-my-zsh
  ansible.builtin.include_tasks: omz/install_omz.yml

- name: Ensure the default shell is set to zsh
  ansible.builtin.include_tasks: ../env/configure_shell.yml

- name: Install the starship shell prompt
  ansible.builtin.include_tasks: prompt/install_starship.yml

